services:
  - type: web
    name: ros-remote-control
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 server.py"
    envVars:
      - key: FLASK_ENV
        value: production
